# Generated by Django 5.2.17 on 2026-10-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoasset',
            name='file',
            field=models.FileField(upload_to='photos/'),
        ),
    ]
