# Generated by Django 5.2.17 on 2026-10-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_albumshare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumshare',
            old_name='exipires_at',
            new_name='expires_at',
        ),
    ]
