# Generated by Django 5.2.17 on 2026-10-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_rename_exipires_at_albumshare_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPhotoDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
