# Generated by Django 5.2.17 on 2026-10-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_album_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumphoto',
            name='source_drive_file_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='albumphoto',
            constraint=models.UniqueConstraint(fields=('album', 'source_drive_file_id'), name='unique_album_drive_file'),
        ),
    ]
