# Generated by Django 5.2.17 on 2026-10-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_albumphoto_source_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='is_deleted',
            field=models.BooleanField(db_column='isdeleted', default=False),
        ),
        migrations.AddField(
            model_name='albumphoto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumphoto',
            name='is_deleted',
            field=models.BooleanField(db_column='isdeleted', default=False),
        ),
    ]
